[profile.default]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./images/" }
]
ffi = true

remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
              'foundry-devops/=lib/foundry-devops/',
              'forge-std/=lib/forge-std/src/',
              'src/=src/',
              'script/=script/']

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config